//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meisy.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meisy.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount cannot be equal or less than zero!.
        /// </summary>
        public static string AMOUNT_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cost per hour cannot be less than zero!.
        /// </summary>
        public static string COST_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("COST_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description cannot be empty!.
        /// </summary>
        public static string EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("EMPTY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email cannot be empty!.
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty!.
        /// </summary>
        public static string EMPTY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product inputs cannot be empty!.
        /// </summary>
        public static string EMPTY_PRODUCT_INPUTS {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_INPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input was not found!.
        /// </summary>
        public static string INPUT_NOT_FOUND {
            get {
                return ResourceManager.GetString("INPUT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company ID is invalid!.
        /// </summary>
        public static string INVALID_COMPANY_ID {
            get {
                return ResourceManager.GetString("INVALID_COMPANY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and/or password incorrect!.
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is invalid!.
        /// </summary>
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid!.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input ID is invalid!.
        /// </summary>
        public static string INVALID_INPUT_ID {
            get {
                return ResourceManager.GetString("INVALID_INPUT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is invalid!.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value for measurement unit is invalid!.
        /// </summary>
        public static string INVALID_VALUE_FOR_MEASUREMENT_UNIT {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_MEASUREMENT_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value for production measurement unit is invalid!.
        /// </summary>
        public static string INVALID_VALUE_FOR_PRODUCTION_MEASUREMENT_UNIT {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_PRODUCTION_MEASUREMENT_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value for type is invalid!.
        /// </summary>
        public static string INVALID_VALUE_FOR_TYPE {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit for this type of overhead has been reached!.
        /// </summary>
        public static string OVERHEAD_LIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("OVERHEAD_LIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This overhead was not found!.
        /// </summary>
        public static string OVERHEAD_NOT_FOUND {
            get {
                return ResourceManager.GetString("OVERHEAD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price cannot be equal or less than zero!.
        /// </summary>
        public static string PRICE_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRICE_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product was not found!.
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The production amount cannot be equal or less than zero!.
        /// </summary>
        public static string PRODUCTION_AMOUNT_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCTION_AMOUNT_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The production time cannot be equal or less than zero!.
        /// </summary>
        public static string PRODUCTION_TIME_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCTION_TIME_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The servings cannot be equal or less than zero!.
        /// </summary>
        public static string SERVINGS_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("SERVINGS_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has already been taken!.
        /// </summary>
        public static string UNAVAILABLE_EMAIL {
            get {
                return ResourceManager.GetString("UNAVAILABLE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no company with this ID!.
        /// </summary>
        public static string UNEXISTENT_COMPANY {
            get {
                return ResourceManager.GetString("UNEXISTENT_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred!.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
