//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meisy.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meisy.Exception.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade não pode ser igual ou menor que zero!.
        /// </summary>
        public static string AMOUNT_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("AMOUNT_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este cliente não foi encontrado!.
        /// </summary>
        public static string CLIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O custo por hora não pode ser igual ou menor que zero!.
        /// </summary>
        public static string COST_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("COST_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A description não pode ficar vazia!.
        /// </summary>
        public static string EMPTY_DESCRIPTION {
            get {
                return ResourceManager.GetString("EMPTY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não pode ficar vazio!.
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ficar vazio!.
        /// </summary>
        public static string EMPTY_NAME {
            get {
                return ResourceManager.GetString("EMPTY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os insumos do produto não podem ficar vazios!.
        /// </summary>
        public static string EMPTY_PRODUCT_INPUTS {
            get {
                return ResourceManager.GetString("EMPTY_PRODUCT_INPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este insumo não pode ser deletado!.
        /// </summary>
        public static string INPUT_BEING_USED {
            get {
                return ResourceManager.GetString("INPUT_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este insumo não foi encontrado!.
        /// </summary>
        public static string INPUT_NOT_FOUND {
            get {
                return ResourceManager.GetString("INPUT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do cliente não é válido!.
        /// </summary>
        public static string INVALID_CLIENT_ID {
            get {
                return ResourceManager.GetString("INVALID_CLIENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da empresa não é válido!.
        /// </summary>
        public static string INVALID_COMPANY_ID {
            get {
                return ResourceManager.GetString("INVALID_COMPANY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email e/ou senha incorretos!.
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data não é válida!.
        /// </summary>
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email não é válido!.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do insumo não é válido!.
        /// </summary>
        public static string INVALID_INPUT_ID {
            get {
                return ResourceManager.GetString("INVALID_INPUT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não é válida!.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone não é válido!.
        /// </summary>
        public static string INVALID_PHONE {
            get {
                return ResourceManager.GetString("INVALID_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID do produto não é válido!.
        /// </summary>
        public static string INVALID_PRODUCT_ID {
            get {
                return ResourceManager.GetString("INVALID_PRODUCT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este valor para unidade de medida não é válido!.
        /// </summary>
        public static string INVALID_VALUE_FOR_MEASUREMENT_UNIT {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_MEASUREMENT_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este valor para unidade de medida de produção não é válido!.
        /// </summary>
        public static string INVALID_VALUE_FOR_PRODUCTION_MEASUREMENT_UNIT {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_PRODUCTION_MEASUREMENT_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este valor para status não é válido!.
        /// </summary>
        public static string INVALID_VALUE_FOR_STATUS {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este valor para o tipo não é válido!.
        /// </summary>
        public static string INVALID_VALUE_FOR_TYPE {
            get {
                return ResourceManager.GetString("INVALID_VALUE_FOR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este pedido não foi encontrado!.
        /// </summary>
        public static string ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este pedido já foi cancelado ou finalizado!.
        /// </summary>
        public static string ORDER_STATUS_COMPLETED {
            get {
                return ResourceManager.GetString("ORDER_STATUS_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O limite para esse tipo de custo indireto já foi atingido!.
        /// </summary>
        public static string OVERHEAD_LIMIT_EXCEEDED {
            get {
                return ResourceManager.GetString("OVERHEAD_LIMIT_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este custo indireto não foi encontrado!.
        /// </summary>
        public static string OVERHEAD_NOT_FOUND {
            get {
                return ResourceManager.GetString("OVERHEAD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço não pode ser igual ou menor que zero!.
        /// </summary>
        public static string PRICE_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRICE_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este produto não pode ser deletado!.
        /// </summary>
        public static string PRODUCT_BEING_USED {
            get {
                return ResourceManager.GetString("PRODUCT_BEING_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este produto não foi encontrado!.
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de produção não pode ser igual ou menor que zero!.
        /// </summary>
        public static string PRODUCTION_AMOUNT_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCTION_AMOUNT_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tempo de produção não pode ser igual ou menor que zero!.
        /// </summary>
        public static string PRODUCTION_TIME_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("PRODUCTION_TIME_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As porções não podem ser igual ou menor que zero!.
        /// </summary>
        public static string SERVINGS_LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("SERVINGS_LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este email já está em uso!.
        /// </summary>
        public static string UNAVAILABLE_EMAIL {
            get {
                return ResourceManager.GetString("UNAVAILABLE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhuma empresa com esse ID!.
        /// </summary>
        public static string UNEXISTENT_COMPANY {
            get {
                return ResourceManager.GetString("UNEXISTENT_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro desconhecido aconteceu!.
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuário não foi encontrado!.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
